In [5]:
import pandas as pd

In [6]:
import pandas as pd

In [7]:
data = pd.read_csv(r"C:\Users\DELL\Downloads\trends.csv")

In [8]:
data.head()

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [9]:
data.shape

(26955, 5)

In [10]:
data.tail()

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 26955 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26955 non-null  str
 1   year      26955 non-null  int64
 2   category  26955 non-null  str
 3   rank      26955 non-null  int64
 4   query     26955 non-null  str
dtypes: int64(2), str(3)
memory usage: 1.0 MB

In [12]:
data.describe()

               year         rank
count  26955.000000  26955.00000
mean    2015.243369      3.00000
std        3.564683      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

In [13]:
data.columns

Index(['location', 'year', 'category', 'rank', 'query'], dtype='str')

In [14]:
data.dtypes

location      str
year        int64
category      str
rank        int64
query         str
dtype: object

In [15]:
data.isnull().sum()

location    0
year        0
category    0
rank        0
query       0
dtype: int64

In [16]:
data.duplicated().sum()

np.int64(10)

In [17]:
data.nunique()

location       83
year           20
category     2450
rank            5
query       18431
dtype: int64

In [18]:
data.shape

(26955, 5)